version: '3'
services:
  payment_postgres:
    image: postgres:11
    container_name: payment_postgres
    restart: always
    environment:
      - POSTGRES_DB=db_payment_postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5434:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  order-db:
    image: mongo
    container_name: order-db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db
  sales_rabbit:
    image: rabbitmq:3-management
    container_name: rabbit-mq
    restart: always
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
  token-redis:
    container_name: token-redis
    image: redis:latest
    ports:
      - "6379:6379"
  auth-db:
    image: postgres:11
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_DB=db_user
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5430:5432
    volumes:
      - ./data/postgres-auth:/var/lib/postgresql/data