server:
  port: 8085
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth_ms
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**
        - id: order_ms
          uri: http://localhost:8081
          predicates:
            - Path=/order/**
        - id: payment_ms
          uri: http://localhost:8080
          predicates:
            - Path=/payment/**